/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.andersonl121.jokenpo.view;

import br.com.andersonl121.jokenpo.controller.CalculoGanhadorRodada;
import br.com.andersonl121.jokenpo.controller.Joga;
import br.com.andersonl121.jokenpo.model.JogadaEnum;
import br.com.andersonl121.jokenpo.model.Jogo;
import br.com.andersonl121.jokenpo.model.Rodada;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson
 */
public class Jogadas extends javax.swing.JFrame {

    /**
     * Creates new form Jogadas
     */
    private int rodada = 1;
    Jogo jogo;
    Random random = new Random();

    public Jogadas(Jogo jogo) {

        initComponents();
        this.jogo = jogo;
        jLabelJogador1.setText(Jogo.getJogador1().getNome());
        jLabelJogador2.setText(Jogo.getJogador2().getNome());
        jLabelJogada.setText(Integer.toString(rodada));
        jLabelJogadaComputador.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPontos2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPontos1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelJogada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxJogada = new javax.swing.JComboBox<>();
        jButtonJogar = new javax.swing.JButton();
        jLabelJogador1 = new javax.swing.JLabel();
        jLabelJogador2 = new javax.swing.JLabel();
        jLabelJogadaComputador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jokenpó");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 140));

        jLabelPontos2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabelPontos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPontos2.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPontos2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPontos2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(140, 140));

        jLabelPontos1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabelPontos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPontos1.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPontos1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPontos1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setText("Jogada:");

        jLabelJogada.setFont(new java.awt.Font("Tempus Sans ITC", 2, 12)); // NOI18N
        jLabelJogada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJogada.setText("0");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel3.setText("Escolha sua Jogada:");

        jComboBoxJogada.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jComboBoxJogada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Pedra", "Papel", "Tesoura" }));
        jComboBoxJogada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJogadaItemStateChanged(evt);
            }
        });

        jButtonJogar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jButtonJogar.setText("Jogar");
        jButtonJogar.setToolTipText("");
        jButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarActionPerformed(evt);
            }
        });

        jLabelJogador1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelJogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJogador1.setText("Jogador1");

        jLabelJogador2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelJogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJogador2.setText("Jogador2");

        jLabelJogadaComputador.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabelJogadaComputador.setText("Computador jogou Pedra");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonJogar)
                        .addGap(36, 134, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelJogador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabelJogadaComputador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelJogada))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonJogar))
                .addGap(26, 26, 26)
                .addComponent(jLabelJogadaComputador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabelJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarActionPerformed

        if (rodada < 10) {
            Jogo.getRodadas().add(new Rodada(rodada));
            
            if (jComboBoxJogada.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Selecione uma opção para jogar", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                switch (jComboBoxJogada.getSelectedIndex()) {
                    case 1:
                        //Jogo.getRodadas().get(rodada-1).setJogada1(JogadaEnum.PEDRA);
                        //break;
                        new Joga(JogadaEnum.PEDRA, Jogo.getJogador1()).Jogar();
                        break;
                    case 2:
                        new Joga(JogadaEnum.PAPEL, Jogo.getJogador1()).Jogar();
                        break;
                    case 3:
                        new Joga(JogadaEnum.TESOURA, Jogo.getJogador1()).Jogar();
                        break;
                }

                JogadaEnum jogadaComputador = new Joga(Jogo.getJogador2()).Jogar();
                
                jLabelJogadaComputador.setText("Computador jogou "+ jogadaComputador.toString());
                jLabelJogadaComputador.setVisible(true);
                
                Jogo.getRodadas().get(rodada - 1).setGanhadorRodada(new CalculoGanhadorRodada(jogo, rodada - 1).calculaGanhador());

                if (Jogo.getRodadas().get(rodada - 1).getGanhadorRodada() != null) {
                    System.out.println("Ganhador da Rodada: " + Jogo.getRodadas().get(rodada - 1).getGanhadorRodada().getNome());

                } else {
                    System.out.println("Rodada deu Empate.");

                }

                rodada = rodada + 1;

                jLabelPontos1.setText(Integer.toString(jogo.getPontosJogador(Jogo.getJogador1())));
                jLabelPontos2.setText(Integer.toString(jogo.getPontosJogador(Jogo.getJogador2())));
                jLabelJogada.setText(Integer.toString(rodada));
                jComboBoxJogada.setSelectedIndex(0);
            }
        }else{
            FimJogo fimJogo  = new FimJogo();
            fimJogo.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_jButtonJogarActionPerformed

    private void jComboBoxJogadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJogadaItemStateChanged
        
        if(jComboBoxJogada.getSelectedIndex()!=0){
            jLabelJogadaComputador.setVisible(false);
        }
        
    }//GEN-LAST:event_jComboBoxJogadaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Jogadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJogar;
    private javax.swing.JComboBox<String> jComboBoxJogada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelJogada;
    private javax.swing.JLabel jLabelJogadaComputador;
    private javax.swing.JLabel jLabelJogador1;
    private javax.swing.JLabel jLabelJogador2;
    private javax.swing.JLabel jLabelPontos1;
    private javax.swing.JLabel jLabelPontos2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
